en.MyAppName=Firebird %1 Database Server %2
en.ServerInstall=Full installation of server and development tools.
en.DeveloperInstall=Installation of client tools for developers and database administrators.
en.ClientInstall=Minimum client install - no server, no tools.
en.CustomInstall=Custom installation
en.ServerComponent=Server components
en.DevAdminComponent=Developer and admin tools components
en.ClientComponent=Client components
en.UseGuardianTask=Use the &Guardian to control the server?
en.UseApplicationTaskMsg=Run as an &Application?
en.TaskGroupDescription=Run Firebird server as:
en.UseServiceTask=Run as a &Service?
en.AutoStartTask=Start &Firebird %1 automatically everytime you boot up?
en.CopyFbClientToSysTask=Copy &Firebird %1 client library to <system> directory?
en.CopyFbClientAsGds32Task=Generate client library as GDS32.DLL for &legacy app. support?
en.InstallCPLAppletTask="Install Control &Panel Applet?"
en.instreg=Updating the registry
en.instclientCopyFbClient=Copying fbclient to the <sys> directory
en.instclientGenGds32=Generating gds32.dll for <sys> directory
en.instclientDecLibCountGds32="Decrementing shared lib count for gds32 and removing it if appropriate."
en.instclientDecLibCountFbClient="Decrementing shared lib count for fbclient and removing it if appropriate."
en.instsvcSetup=Setting up the service
en.instsvcStartQuestion=Start Firebird Service now?
en.instsvcStartMsg=Starting the server
en.instsvcStopMsg="Stopping the service"
en.instsvcRemove="Removing the service"
en.instappStartQuestion=Start Firebird now?
en.instappStartMsg=Starting the server

en.InstallSummarySuffix1=This version of Firebird %1 will become the default install.
en.InstallSummarySuffix2=Also, take note that installing this version of Firebird %1 
en.InstallSummarySuffix3= when a later version is already installed may lead to
en.InstallSummarySuffix4=                 unpredictable results.

en.InstallSummaryCancel1= If you continue with this installation Firebird %1 will be installed but not configured.
en.InstallSummaryCancel2= You will have to complete installation manually.
en.InstallSummaryCancel3= Do you want to CANCEL this installation?

en.InstalledProducts='re-installation analysis indicates that %s existing Firebird or Interbase %s been found.
en.InstalledProdCountSingular=version has
en.InstalledProdCountPlural=versions have

en.FbRunning1=An existing Firebird %1 Server is running.
en.FbRunning2= You must close the application or stop the
en.FbRunning3=         service before continuing.

en.PreviousInstallBroken=   (Install appears broken due to version string mismatch.)
en.PreviousInstallGood=   (Installation appears to be correct.)

en.IconReadme=Firebird %1 %2 Readme
en.IconUninstall=Uninstall Firebird %1 
en.ReleaseNotes= release notes. (Requires Acrobat Reader.)
en.Uninstall=Uninstall Firebird
en.Winsock2Web1=Winsock 2 is not installed.
en.Winsock2Web2=Would you like to Visit the Winsock 2 Update Home Page?
en.NoWinsock2 = Please Install Winsock 2 Update before continuing
en.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

en.RunCSNoGuardian=Run Firebird classic server (without guardian)
en.RunSSNoGuardian=Run Firebird Superserver (without guardian)
en.RunSSWithGuardian=Run Firebird Super Server (with guardian)
en.RunCSWithGuardian=Run Firebird Classic Server (with guardian)
en.RunISQL=Run command-line based Interactive SQL tool

en.ReadmeFile=readme.txt
en.InstallationReadmeFile=installation_readme.txt


