#!/bin/bash
VULCAN=$(cd ../install; pwd;)
PATH=$VULCAN/bin:$PATH
LD_LIBRARY_PATH=$VULCAN/bin:$VULCAN/bin64:$LD_LIBRARY_PATH
export VULCAN
export PATH
export LD_LIBRARY_PATH
rm -f $VULCAN/bin/*.so \
	$VULCAN/bin/config \
	$VULCAN/bin/gpre \
	$VULCAN/bin/gbak \
	$VULCAN/bin/qli \
	$VULCAN/bin/isql \
	$VULCAN/firebird.msg \
	$VULCAN/security.fdb \
	$VULCAN/databases/msg.fdb \
	$VULCAN/help/help.fdb > /dev/null 2>&1

for x in why config gpre remote jrd burp msgs qli isql server intlcpp IscDbc lock alice gsec gstat Services XLoad; do
	(
	cd $x
	echo
	echo "boot_build: Entering directory \`$PWD'"
	echo Building $x
	echo
	./gen
	if [ -e boot ] ; then ./boot ; fi
	gmake
	gmake install
	)
done
