#!/bin/bash
VULCAN=$(cd ../install; pwd;)
PATH=$VULCAN/bin:$PATH
LD_LIBRARY_PATH=$VULCAN/bin:$VULCAN/bin64:$LD_LIBRARY_PATH
export VULCAN
export PATH
export LD_LIBRARY_PATH

for x in config why gpre remote jrd intlcpp burp isql qli server lock IscDbc XLoad ; do
	(
	cd $x
	echo
	echo "build: Entering directory \`$PWD'"
	echo Building $x
	echo
	./gen $*
	gmake
	gmake install
	)
done
