#!/bin/bash

for x in config why gpre remote jrd burp msgs isql qli server intlcpp IscDbc lock alice gsec gstat Services XLoad; do
	(
	cd $x
	echo
	echo Make dependencies for  $x
	echo
	gmake dependencies
	)
done
