#!/bin/bash
echo $1
if [ -e ../install/bin/buildgen ] ; then rm ../install/bin/buildgen ; fi
ln -s  buildgen.$1 ../install/bin/buildgen
cat <<end >setup.sed
s/proto/$1/
end
for x in config gpre why jrd remote intlcpp burp msgs qli isql server lock IscDbc XLoad ThreadTest ; do
	(
	echo $x
	cd $x
	if [ -e gen ] ; then rm gen; fi;
	sed  -f ../setup.sed gen.proto > gen.temp
	mv gen.temp gen.$1
	chmod +x gen.$1
	ln -s gen.$1 gen
	if [ ! -e makefile.in ] ; then cp /dev/null makefile.in ; fi
	if [ -e boot ] ; then chmod +x boot ; fi
	)
done
rm setup.sed
